### ISSUE TITLE
Do not check if the database exists using a localized string

### ISSUE THREAD

**Issue by mardukbp** [nilaysavant/mediocre#13]
Mediocre Editor fails to start in Windows 10 with German as main language, due to
src/models/app_db_state.rs:27 expecting an error message in English.

e.to_string().contains("(os error 2)") is a better solution, but even better would be to explicitly check if the file exists instead of depending on error message strings.

**Comment by nilaysavant** [comment]
Hey, Thanks for checking out mediocre!

Will try to implement the solution you suggested ie. checking if the db file exist on the `db_path` before proceeding to `PickleDb::load()`.

**Comment by mardukbp** [comment]
I can confirm that the patch works. I would suggest you publish a release so that anyone who does not have an English OS can try Mediocre :) While you are at it, since Tauri 1.0 is already out, you could upgrade the JS and Rust Tauri packages. Thanks!

**Comment by nilaysavant** [comment]
> I can confirm that the patch works. I would suggest you publish a release so that anyone who does not have an English OS can try Mediocre :) While you are at it, since Tauri 1.0 is already out, you could upgrade the JS and Rust Tauri packages. Thanks!

Sure! I'll be publishing the release by the end of this week.

The upgrade to Tauri 1.0 might take a bit longer though.
